pipeline:
  identifier: Build_python_1698667154968
  name: Build python
  orgIdentifier: default
  projectIdentifier: python
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698667091809
        repoName: ayushkh1012/python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_python_app
                  name: Build Python App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      python -m pip install --upgrade pip
                      pip install  pytest
                      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
